STAGING : Remove some unused components for penkek
Signed-off-by: Raphiel Rollerscaperers <raphielscape@outlook.com>

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -122,13 +122,12 @@ ui_print "Checking Treble or nah..."
 mount -o rw,remount -t auto /system;
 mount -o rw,remount -t auto /vendor 2>/dev/null;
 if [ "$(file_getprop /system/build.prop ro.treble.enabled)" == "true" ]; then
-  ui_print "Treble bois~"
+  ui_print "Swoosh..."
   rm -rf /vendor/etc/perf
   dtb=/tmp/anykernel/treble;
 else
-  ui_print="Oof, move to treble soon plz"
-  rm -rf /system/vendor/etc/perf
-  dtb=/tmp/anykernel/nontreble;
+  ui_print="Excuse me, what the duck"
+  rm -rf /system/vendor/etc/perf;
 fi;
 mount -o ro,remount -t auto /system;
 mount -o ro,remount -t auto /vendor 2>/dev/null;
@@ -145,10 +144,13 @@ done;
 if [ $? != 0 -o -z "$(ls /tmp/anykernel/bin)" ]; then
   abort "Recovery busybox setup failed. Aborting...";
 fi;
-cat /tmp/anykernel/kernel/Image.gz $dtb/*.dtb > /tmp/anykernel/Image.gz-dtb;
-if [ $? != "0" ]; then
-  abort "DTB append failed. Aborting...";
-fi;
+
+# FIXME : penkek requires treble, deprecate this later
+# cat /tmp/anykernel/kernel/Image.gz $dtb/*.dtb > /tmp/anykernel/Image.gz-dtb;
+# if [ $? != "0" ]; then
+#   abort "DTB append failed. Aborting...";
+# fi;
+
 PATH="/tmp/anykernel/bin:$PATH" $bb ash /tmp/anykernel/anykernel.sh $2;
 if [ $? != "0" ]; then
   abort;
